In [27]:
import pandas as pd

In [20]:
def load_csv(csv):
    return pd.read_csv(csv)

In [28]:
combined_df = pd.DataFrame()
for x in range(2006, 2021):
   current_df = pd.read_csv(f'../gun_deaths_2006-2020/gun_data_2006-2020/guns_{x}.csv')
   combined_df = pd.concat([combined_df, current_df], ignore_index=True)

In [31]:
combined_df.drop('hispanic', axis=1, inplace=True)

In [40]:
combined_df.rename(columns={'sex':'victim_sex', 'age':'victim_age', 'race':'victim_race', 'education':'victim_education'}, inplace=True)

In [41]:
combined_df

,year,month,intent,police,victim_sex,victim_age,victim_race,place,victim_education
0,2006,1,Suicide,0,M,81.0,White,Home,HS/GED
1,2006,1,Homicide,0,M,55.0,White,Other unspecified,Less than HS
2,2006,1,Homicide,0,M,19.0,Black,Home,Less than HS
3,2006,1,Homicide,0,M,33.0,Black,Other unspecified,Less than HS
4,2006,1,Homicide,0,M,23.0,Black,Home,Less than HS
...,...,...,...,...,...,...,...,...,...
529228,2020,12,Suicide,0,M,35.0,Hispanic,Home,Some college
529229,2020,12,Homicide,0,M,34.0,Black,Street,HS/GED
529230,2020,12,Homicide,0,M,26.0,Black,Street,HS/GED
529231,2020,12,Homicide,0,M,24.0,Black,Trade/service area,HS/GED
529232,2020,12,Homicide,1,M,18.0,Hispanic,NaN,HS/GED

In [42]:
combined_df.to_csv('combined_gun_data.csv', index=False)